### ISSUE TITLE
Incorrect Derivative Formula

### ISSUE THREAD

**Issue by mark-barbour** [learn-co-curriculum/dsc-gradient-descent-in-3d#3]
## Link to Canvas

https://learning.flatironschool.com/courses/6216/assignments/222914?module_item_id=520716
https://github.com/learn-co-curriculum/dsc-gradient-descent-in-3d

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X] Other (explain below)

### Source

```
$$\frac{df}{dy}f(x,y) =  \frac{df}{dy}(y) * x^2 = 1*x^2 = x^2$$
```

### Concern

x^2 isn’t a constant.  It needs to be differentiated with respect to y.  The 2nd term should be: 2x*dx/dy.

## (Optional) Proposed Solution

```
$$\frac{df}{dy}f(x,y) =  \frac{df}{dy}(y) * x^2 = 1*x^2 = 2x$$
```

## What OS Are You Using?

- [X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

<img width="977" alt="image" src="https://user-images.githubusercontent.com/92879357/236320444-dff2b347-d3ce-4482-8504-f58decdbceb1.png">

**Comment by jessepisel** [comment]
@mark-barbour It has been a while since I have done partials by hand but is it correct that if we take the derivative with respect to y then we do not care about what x is doing which makes it a constant? I checked [Wolfram](https://www.wolframalpha.com/input?i=partial+derivative+of+y*x**2+with+respect+to+y) and it what is in the notebook looks correct.
